### PR TITLE
Telepathy and Hyperlane adapter contracts

### PR DESCRIPTION
**Pull request by don17raden**
GM,

We are participants of the ongoing ETHGlobal Scaling Ethereum hackathon. We came to know of a track sponsored by Gnosis Chain for projects on Hashi. Our project is titled 'Paalam' and it revolves around building custom oracle adapters for Hashi. We have created two adapters, which make use of the [Telepathy](https://www.telepathy.xyz/) and [Hyperlane](https://www.hyperlane.xyz/) interoperability protocols. This PR contains the set of contracts we have built and we hope this counts as a valid submission towards the hackathon track.

Thanks and Regards.

### CODE REVIEW

**Comment by auryn-macmillan** [comment]
Thanks for the PR!

Worth noting that we'll probably move the historical proving logic in `OracleAdapter` into a a separate contract, so that OracleAdapters that are not aggregating execution layer headers aren't importing redundant logic.

**Comment by auryn-macmillan** [comment]
Oh, actually, @lrnt already did this! 😅

@don17raden, could you update the PR to import `BlockHashOracleAdapter` if it's reporting execution layer block hashes?

**Comment by don17raden** [comment]
Hey @auryn-macmillan,

Looks like there has been a new PR with Telepathy. How about I skim this PR such that it's just the Hyperlane adapter?

**Comment by auryn-macmillan** [comment]
Yeah, I think that makes sense @don17raden.

**Comment by auryn-macmillan** [comment]
Closing due to inactivity.
Let me know if you'd like to re-open this, @don17raden.

**Pull request closed without merging**
